<?php
/**
 * presensi-siswa
 * LaporanController.php
 * Author: DwiAgus
 * Email : dwiagus@uny.ac.id
 * Date  : 10/07/2020
 * Time  : 20:09
 */

namespace Modules\Presensi\Controllers;


use Modules\Frontend\Controllers\ControllerBase;
use Modules\History\Models\History;
use Modules\Kelas\Models\Kelas;
use Modules\Libur\Models\Libur;
use Modules\Presensi\Plugin\Base64Url;
use Modules\Presensi\Plugin\Helper;
use Modules\Tahunajaran\Models\Tahunajaran;
use Modules\Webconfig\Models\Webconfig;
use Phalcon\Assets\Filters\Jsmin;
use Phalcon\Mvc\Model\ResultsetInterface;
use Phalcon\Mvc\View;

class LaporanController extends ControllerBase
{
    /**
     * @var ResultsetInterface|void
     */
    private $tahun;
    /**
     * @var ResultsetInterface|void
     */
    private $kelas;
    private $terlambat;
    private $pulangawal_normal;
    private $pulangawal_jumat;
    private $nip_kepsek;
    private $nama_kepsek;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->tahun = Tahunajaran::find();
        $this->kelas = Kelas::find("status='1'");
        $this->assets
            ->collection('footer')
            ->setTargetPath("themes/admin/assets/js/combined-presensi-laporan.js")
            ->setTargetUri("themes/admin/assets/js/combined-presensi-laporan.js")
            ->join(true)
            ->addJs($this->config->application->addonsDir."presensi/views/js/laporan.js")
            ->addFilter(new Jsmin());
        $this->webConfig();
    }

    public function indexAction()
    {

    }

    public function search_harianAction()
    {
        if ($this->request->isPost() == true)
        {
            $kelas = $this->request->getPost("kelas");
            $tahun = $this->request->getPost("tahun_ajaran");
            $tanggal    = $this->request->getPost("tanggal");
            $mode       = $this->request->getPost("mode");
            $libur = Libur::findFirst([
                'conditions' => "tanggal= ?1",
                'bind'  => [
                    1 => $tanggal
                ]
            ]);
            $cl = 0;
            if($libur)
            {
                $cl = count($libur);
            }

            $arr = $this->presensiHarian($mode, $kelas, $tahun, $tanggal);
            $this->view->setRenderLevel(
                View::LEVEL_ACTION_VIEW
            );
            $this->view->setVar('tanggal', date('d M Y',strtotime($tanggal)));
            $this->view->setVar('url_print',Base64Url::encode($tahun."/".$tanggal."/".$mode."/".$kelas));
            $this->view->setVar('terlambat',$this->terlambat);
            $this->view->setVar('pulangawal_jumat', $this->pulangawal_jumat);
            $this->view->setVar('pulangawal_normal',$this->pulangawal_normal);
            $this->view->setVar('count_libur', $cl);
            $this->view->setVar('libur',$libur);
            $this->view->setVar('arr',$arr);

            if($mode == 0)
            {
                $this->view->pick('laporan/rekap_normal_harian');
            }else{
                $this->view->pick('laporan/rekap_sesi_harian');
            }
        }
    }

    public function search_bulananAction()
    {
        $kelas = $this->request->getPost('kelas');
        $tahun = $this->request->getPost('tahun_ajaran');
        if(empty($this->request->getPost('bulan')))
        {
            $bulan = date('m-Y');
        }else{
            $bulan = $this->request->getPost('bulan');
        }
        $mode  = $this->request->getPost('mode');
        $libur = Libur::find([
            'conditions' => "DATE_FORMAT(tanggal,'%m-%Y')= ?1",
            'bind'  => [
                1 => $bulan
            ]
        ]);
        $arr = $this->presensiBulanan($mode, $kelas, $tahun, $bulan);
        $work = $this->workBulanan($bulan);
        $this->view->setRenderLevel(
            View::LEVEL_ACTION_VIEW
        );
        $this->view->setVar('url_print',Base64Url::encode($tahun."/".$bulan."/".$mode."/".$kelas));
        $this->view->setVar('terlambat',$this->terlambat);
        $this->view->setVar('pulangawal_jumat', $this->pulangawal_jumat);
        $this->view->setVar('pulangawal_normal',$this->pulangawal_normal);
        $this->view->setVar('count_work',count($work));
        $this->view->setVar('work',$work);
        $this->view->setVar('count_libur', count($libur->toArray()));
        $this->view->setVar('libur',$libur->toArray());
        $this->view->setVar('arr',$arr);
        if($mode == 0)
        {
            $this->view->pick('laporan/rekap_normal_bulanan');
        }else{
            $this->view->pick('laporan/rekap_sesi_bulanan');
        }
    }

    public function search_semesterAction()
    {
        $kelas = $this->request->getPost('kelas');
        $tahun = $this->request->getPost('tahun_ajaran');
        $semester = $this->request->getPost('semester');
        list($start, $end) = $this->getSemester($tahun, $semester);
        list($work, $libur, $arr) = $this->presensiSemester($start, $end, $kelas, $tahun);
        //return $arr;
        $this->view->setRenderLevel(
            View::LEVEL_ACTION_VIEW
        );
        $this->view->setVar('url_print',Base64Url::encode($tahun."/".$semester."/".$start."/".$end."/".$kelas));
        $this->view->setVar('work',$work);
        $this->view->setVar('libur',$libur);
        $this->view->setVar('jml_hari',count($work)-$libur->count());
        $this->view->setVar('arr',$arr);
        $this->view->pick("laporan/rekap_semester");
    }

    public function harianAction()
    {
        $this->view->setVar('kelas',$this->kelas);
        $this->view->setVar('tahun',$this->tahun);
        $this->view->pick("laporan/index_harian");
    }

    public function bulananAction()
    {
        $this->view->setVar('kelas',$this->kelas);
        $this->view->setVar('tahun',$this->tahun);
        $this->view->pick("laporan/index_bulanan");
    }

    public function semesterAction()
    {
        $this->view->setVar('kelas',$this->kelas);
        $this->view->setVar('tahun',$this->tahun);
        $this->view->pick("laporan/index_semester");
    }

    public function cetak_bulananAction()
    {
        $geturl = Base64Url::decode($this->request->getQuery('url'));
        list($tahun,$bulan,$mode,$kelas) = explode("/",$geturl);
        $libur = Libur::find([
            'conditions' => "DATE_FORMAT(tanggal,'%m-%Y')= ?1",
            'bind'  => [
                1 => $bulan
            ]
        ]);
        $arr = $this->presensiBulanan($mode, $kelas, $tahun, $bulan);
        $work = $this->workBulanan($bulan);
        $this->view->setRenderLevel(
            View::LEVEL_ACTION_VIEW
        );
        $this->view->setVar('terlambat',$this->terlambat);
        $this->view->setVar('pulangawal_jumat', $this->pulangawal_jumat);
        $this->view->setVar('pulangawal_normal',$this->pulangawal_normal);
        $this->view->setVar('count_work',count($work));
        $this->view->setVar('count_libur', count($libur->toArray()));
        $this->view->setVar('libur',$libur->toArray());
        $this->view->setVar('nip',$this->nip_kepsek);
        $this->view->setVar('kepsek', $this->nama_kepsek);
        $this->view->setVar('kelas',$kelas);
        $this->view->setVar('bulan',date('M Y',strtotime(Helper::firstday($bulan))));
        $this->view->setVar('work',$work);
        $this->view->setVar('arr',$arr);
        if($mode == 0){
            $this->view->pick("laporan/cetak_normal_bulanan");
        }else{
            $this->view->pick("laporan/cetak_sesi_bulanan");
        }

    }

    public function cetak_harianAction()
    {
        $geturl = Base64Url::decode($this->request->getQuery('url'));
        list($tahun,$tanggal,$mode,$kelas) = explode("/",$geturl);
        $arr = $this->presensiHarian($mode, $kelas, $tahun, $tanggal);
        $libur = Libur::findFirst([
            'conditions' => "tanggal= ?1",
            'bind'  => [
                1 => $tanggal
            ]
        ]);
        $cl = 0;
        if($libur)
        {
            $cl = count($libur);
        }
        $this->view->setRenderLevel(
            View::LEVEL_ACTION_VIEW
        );
        $this->view->setVar('tanggal', date('d M Y',strtotime($tanggal)));
        $this->view->setVar('terlambat',$this->terlambat);
        $this->view->setVar('pulangawal_jumat', $this->pulangawal_jumat);
        $this->view->setVar('pulangawal_normal',$this->pulangawal_normal);
        $this->view->setVar('count_libur', $cl);
        $this->view->setVar('libur',$libur);
        $this->view->setVar('nip',$this->nip_kepsek);
        $this->view->setVar('kepsek', $this->nama_kepsek);
        $this->view->setVar('kelas',$kelas);
        $this->view->setVar('tanggal',date('d M Y',strtotime($tanggal)));
        $this->view->setVar('arr',$arr);
        if($mode == 0){
            $this->view->pick("laporan/cetak_normal_harian");
        }else{
            $this->view->pick("laporan/cetak_sesi_harian");
        }
    }

    public function cetak_semesterAction()
    {
        $geturl = Base64Url::decode($this->request->getQuery('url'));
        list($tahun,$semester,$start,$end,$kelas) = explode("/",$geturl);
        list($work, $libur, $arr) = $this->presensiSemester($start, $end, $kelas, $tahun);
        $this->view->setRenderLevel(
            View::LEVEL_ACTION_VIEW
        );
        $this->view->setVar('nip',$this->nip_kepsek);
        $this->view->setVar('kepsek', $this->nama_kepsek);
        $this->view->setVar('kelas',$kelas);
        $this->view->setVar('semester',$semester);
        $this->view->setVar('tahun',$tahun);
        $this->view->setVar('work',$work);
        $this->view->setVar('libur',$libur);
        $this->view->setVar('jml_hari',count($work)-$libur->count());
        $this->view->setVar('arr',$arr);
        $this->view->pick("laporan/cetak_semester");
    }

    /**
     * @param $mode
     * @param $kelas
     * @param $tahun
     * @param $bulan
     * @return array
     */
    public function presensiBulanan($mode, $kelas, $tahun, $bulan)
    {
        if ($mode == 0) {
            $isMode = 'AND sesi=0';
        } else {
            $isMode = 'AND sesi <> 0';
        }
        $history = History::find([
            'conditions' => "kelas= ?1 AND tahun= ?2",
            'bind' => [
                1 => $kelas,
                2 => $tahun
            ]
        ]);
        $arr = array();
        foreach ($history as $siswa) {
            $arr[] = [
                'nisn' => $siswa->nisn,
                'nama' => $siswa->nama,
                'sex' => $siswa->sex,
                'presensi' => $siswa->getPresensi(
                    ['conditions' => "tahun_ajaran='{$tahun}' AND DATE_FORMAT(tanggal,'%m-%Y') = '{$bulan}' " . $isMode]),
            ];
        }
        return $arr;
    }

    /**
     * @param $bulan
     * @return array
     */
    public function workBulanan($bulan)
    {
        $start = Helper::firstday($bulan);
        $end = Helper::lastDay($bulan);
        return Helper::workingDay($start, $end);
    }

    /**
     * @param $mode
     * @param $kelas
     * @param $tahun
     * @param $tanggal
     * @return array
     */
    public function presensiHarian($mode, $kelas, $tahun, $tanggal)
    {
        if ($mode == 0) {
            $isMode = 'AND sesi=0';
        } else {
            $isMode = 'AND sesi <> 0';
        }
        $presensi = History::find([
            'conditions' => 'kelas= ?1 AND tahun= ?2',
            'bind' => [
                1 => $kelas,
                2 => $tahun,
            ]
        ]);
        $arr = array();
        foreach ($presensi as $siswa) {
            $arr[] = [
                'nisn' => $siswa->nisn,
                'nama' => $siswa->nama,
                'sex' => $siswa->sex,
                'presensi' => $siswa->getPresensi(
                    ['conditions' => "tahun_ajaran='{$tahun}' AND tanggal = '{$tanggal}' " . $isMode]),
            ];
        }
        return $arr;
    }

    public function webConfig()
    {
        foreach (Webconfig::find()->toArray() as $k => $v) {
            if ($v['name'] == 'jam_terlambat') {
                $this->terlambat = $v['content'];
            }
            if ($v['name'] == 'jam_pulang_awal_jumat') {
                $this->pulangawal_jumat = $v['content'];
            }
            if ($v['name'] == 'jam_pulang_awal_normal') {
                $this->pulangawal_normal = $v['content'];
            }
            if ($v['name'] == 'kepala_sekolah') {
                $this->nama_kepsek = $v['content'];
            }
            if ($v['name'] == 'nip_kepala_sekolah') {
                $this->nip_kepsek = $v['content'];
            }
        }
    }

    /**
     * @param $tahun
     * @param $semester
     * @return array
     */
    public function getSemester($tahun, $semester)
    {
        list($th_start, $th_end) = explode("-", $tahun);
        if ($semester == "1") {
            $start = $th_start . "-07-01";
            $end = Helper::lastDay("12-" . $th_start);
        } else {
            $start = $th_end . "-01-01";
            $end = Helper::lastDay("07-" . $th_end);
        }
        return array($start, $end);
    }

    /**
     * @param $start
     * @param $end
     * @param $kelas
     * @param $tahun
     * @return array
     */
    public function presensiSemester($start, $end, $kelas, $tahun)
    {
        $work = Helper::workingDay($start, $end);
        $libur = Libur::find([
            'conditions' => "tanggal BETWEEN ?1 AND ?2",
            'bind' => [
                1 => $start,
                2 => $end,
            ]
        ]);
        $history = History::find([
            'conditions' => "kelas= ?1 AND tahun= ?2",
            'bind' => [
                1 => $kelas,
                2 => $tahun
            ]
        ]);
        $arr = array();
        foreach ($history as $siswa) {
            $arr[] = [
                'nisn' => $siswa->nisn,
                'nama' => $siswa->nama,
                'sex' => $siswa->sex,
                'hadir' => $siswa->getPresensi(
                    ['conditions' => "tahun_ajaran='{$tahun}' AND tanggal BETWEEN '{$start}' AND '{$end}' AND status='1'",
                        'columns' => "distinct tanggal"
                    ])->count(),
                'izin' => $siswa->getPresensi(
                    ['conditions' => "tahun_ajaran='{$tahun}' AND tanggal BETWEEN '{$start}' AND '{$end}' AND status='3'",
                        'columns' => "distinct tanggal"
                    ])->count(),
                'sakit' => $siswa->getPresensi(
                    ['conditions' => "tahun_ajaran='{$tahun}' AND tanggal BETWEEN '{$start}' AND '{$end}' AND status='4'",
                        'columns' => "distinct tanggal"
                    ])->count(),
            ];
        }
        return array($work, $libur, $arr);
    }
}