<?php
/**
 * htdocs
 * RiwayatController.php
 * Author: DwiAgus
 * Email : dwiagus@uny.ac.id
 * Date  : 14/07/2020
 * Time  : 23:08
 */

namespace Modules\Presensi\Controllers;


use Modules\Frontend\Controllers\ControllerBase;
use Modules\History\Models\History;
use Modules\Webconfig\Models\Webconfig;

class RiwayatController extends ControllerBase
{


    /**
     * @var mixed|void
     */
    private $terlambat;
    /**
     * @var mixed|void
     */
    private $pulangawal_jumat;
    /**
     * @var mixed|void
     */
    private $pulangawal_normal;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        foreach (Webconfig::find()->toArray() as $k => $v) {
            if($v['name'] == 'jam_terlambat'){
                $this->terlambat = $v['content'];
            }
            if($v['name'] == 'jam_pulang_awal_jumat'){
                $this->pulangawal_jumat = $v['content'];
            }
            if($v['name'] == 'jam_pulang_awal_normal'){
                $this->pulangawal_normal = $v['content'];
            }
        }
    }

    public function personalHarian($mode,$nisn,$tanggal)
    {
        if ($mode == 0) {
            $isMode = 'AND sesi=0';
        } else {
            $isMode = 'AND sesi <> 0';
        }
        $presensi = History::find([
            'conditions' => 'nisn= ?1',
            'bind' => [
                1 => $nisn,
            ]
        ]);
        $arr = array();
        foreach ($presensi as $siswa) {
            $arr[] = [
                'nisn' => $siswa->nisn,
                'nama' => $siswa->nama,
                'sex' => $siswa->sex,
                'presensi' => $siswa->getPresensi(
                    ['conditions' => "tanggal = '{$tanggal}' " . $isMode]),
            ];
        }
        return $arr;

    }

    public function personalBulanan($mode, $nisn, $bulan)
    {
        if ($mode == 0) {
            $isMode = 'AND sesi=0';
        } else {
            $isMode = 'AND sesi <> 0';
        }
        $history = History::find([
            'conditions' => "nisn= ?1",
            'bind' => [
                1 => $nisn,
            ]
        ]);
        $arr = array();
        foreach ($history as $siswa) {
            $arr[] = [
                'nisn' => $siswa->nisn,
                'nama' => $siswa->nama,
                'sex' => $siswa->sex,
                'presensi' => $siswa->getPresensi(
                    ['conditions' => "DATE_FORMAT(tanggal,'%m-%Y') = '{$bulan}' " . $isMode]),
            ];
        }
        return $arr;
    }
}