<?php
/**
 * htdocs
 * RiwayatController.php
 * Author: DwiAgus
 * Email : dwiagus@uny.ac.id
 * Date  : 22/07/2020
 * Time  : 10:02
 */

namespace Modules\Presensi\Controllers;


use Modules\History\Models\History;
use Modules\Libur\Models\Libur;
use Modules\Presensi\Models\Presensi;
use Modules\Presensi\Plugin\Helper;
use Modules\Tahunajaran\Models\Tahunajaran;
use Phalcon\Assets\Filters\Jsmin;
use Phalcon\Mvc\Model;
use Phalcon\Mvc\View;

class RiwayatController extends \Modules\Frontend\Controllers\ControllerBase
{
    /**
     * @var \Phalcon\Mvc\Model\ResultsetInterface|void
     */
    private $tahun;
    /**
     * @var void
     */
    private $siswa;
    /**
     * @var void
     */
    private $tahunajaran;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->tahun = Tahunajaran::find();
        $this->siswa = $this->auth->getIdentity();
        $this->assets
            ->collection('footer')
            ->setTargetPath("themes/admin/assets/js/combined-presensi-riwayat.js")
            ->setTargetUri("themes/admin/assets/js/combined-presensi-riwayat.js")
            ->join(true)
            ->addJs($this->config->application->addonsDir."presensi/views/js/riwayat.js")
            ->addFilter(new Jsmin());
        $this->getTahun();
    }

    public function harianAction()
    {
        $this->view->setVar('tahun',$this->tahun);
        $this->view->pick("riwayat/index_bulanan");
    }

    public function bulananAction()
    {
        $this->view->setVar('tahun',$this->tahun);
        $this->view->pick("riwayat/index_bulanan");
    }

    public function search_bulananAction()
    {
        $tahun  = $this->request->getPost('tahun_ajaran');
        $bulan  = $this->request->getPost('bulan');
        $mode   = $this->request->getPost('mode');
        $nisn   = $this->siswa['email'];
        $presensi = $this->presensiBulanan($mode, $nisn, $tahun, $bulan);

        $this->view->setRenderLevel(
            View::LEVEL_ACTION_VIEW
        );
        $this->view->setVar('presensi',$presensi);
        if ($mode == 0) {
            $this->view->pick('riwayat/normal_bulanan');
        } else {
            $this->view->pick('riwayat/sesi_bulanan');
        }

    }

    public function search_harianAction()
    {

    }

    public function cetak_harianAction()
    {

    }

    public function getTahun()
    {
        foreach ($this->tahun as $item) {
            if ($item->status == '1') {
                $this->tahunajaran = $item->tahun;
            }
        }
    }

    /**
     * @param $mode
     * @param $nisn
     * @param $tahun
     * @param $bulan
     *
     * @throws \Exception
     */
    public function presensiBulanan($mode, $nisn, $tahun, $bulan)
    {
        if ($mode == 0) {
            $isMode = 'AND sesi=0';
        } else {
            $isMode = 'AND sesi <> 0';
        }
        $work   = Helper::workBulanan($bulan);
        $libur = Libur::find([
            'conditions' => "DATE_FORMAT(tanggal,'%m-%Y') = ?1",
            'bind' => [
                1 => $bulan,
            ]
        ]);
        $history = History::findFirst([
            'conditions' => "nisn= ?1",
            'bind' => [
                1 => $nisn,
            ]
        ]);
        $presensi = $history->getPresensi([
            'conditions' => "nisn = '{$nisn}' AND tahun_ajaran = '{$tahun}' AND DATE_FORMAT(tanggal,'%m-%Y') = '{$bulan}' ".$isMode]);

        if($mode == 0){
            $result = $this->resultNormalBulanan($work, $presensi, $history);
        }else{
            $result = $this->resultSesiBulanan($work, $presensi, $history);
        }

        return $result;
    }

    /**
     * @param array $work
     * @param $presensi
     * @param Model $history
     * @return array
     * @throws \Exception
     */
    public function resultNormalBulanan(array $work, $presensi, Model $history)
    {
        $result = array();
        foreach ($work as $w => $wk) {
            foreach ($presensi as $item) {
                if ($item->tanggal == $wk) {
                    if ($item->foto_masuk) {
                        $img_masuk = "/upload/presensi/" . $item->foto_masuk;
                    } else {
                        $img_masuk = "/themes/frontend/images/sma.png";
                    }
                    if ($item->foto_keluar) {
                        $img_keluar = "/upload/presensi/" . $item->foto_keluar;
                    } else {
                        $img_keluar = "/themes/frontend/images/sma.png";
                    }
                    if ($item->jam_masuk) {
                        $jammasuk = new \DateTime($item->jam_masuk);
                        $jam_masuk = $jammasuk->format('H:m:s');
                    } else {
                        $jam_masuk = "";
                    }
                    if ($item->jam_keluar) {
                        $jamkeluar = new \DateTime($item->jam_keluar);
                        $jam_keluar = $jamkeluar->format('H:m:s');
                    } else {
                        $jam_keluar = "";
                    }

                    $result[$wk] = [
                        'tanggal' => $wk,
                        'nama' => $history->nama,
                        'nisn' => $history->nisn,
                        'sex' => $history->sex,
                        'jam_masuk' => $jam_masuk,
                        'jam_keluar' => $jam_keluar,
                        'foto_masuk' => $img_masuk,
                        'foto_keluar' => $img_keluar,
                        'status' => $item->status
                    ];
                    break;
                } else {
                    $result[$wk] = [
                        'tanggal' => $wk,
                        'nama' => $history->nama,
                        'nisn' => $history->nisn,
                        'sex' => $history->sex,
                        'jam_masuk' => "",
                        'jam_keluar' => "",
                        'foto_masuk' => "/themes/frontend/images/sma.png",
                        'foto_keluar' => "/themes/frontend/images/sma.png",
                        'status' => ""
                    ];

                }
            }
        }
        return $result;
    }

    /**
     * @param array $work
     * @param $presensi
     * @param Model $history
     * @return array
     */
    public function resultSesiBulanan(array $work, $presensi, Model $history)
    {
        $pres = array();
        foreach ($presensi as $item){
            $jammasuk = new \DateTime($item->jam_masuk);
            $jam_masuk = $jammasuk->format('H:m:s');
            $pres[] = [
                'tanggal' => $item->tanggal,
                'nama' => $history->nama,
                'nisn' => $history->nisn,
                'sex' => $history->sex,
                'sesi' => $item->sesi,
                'jam_masuk' => $jam_masuk,
                'status'    => $item->status,
            ];
        }
        $result = array();
        foreach ($work as $w => $wk) {
            for ($i = 1; $i <= 5; $i++) {
                foreach ($pres as $item) {
                    if ($item['tanggal'] == $wk) {
                        if ($item['sesi'] == $i) {
                            $result[$wk]['tanggal'] = $wk;
                            $result[$wk]['nama'] = $history->nama;
                            $result[$wk]['nisn'] = $history->nisn;
                            $result[$wk]['sex'] = $history->sex;
                            $result[$wk]['status'] = $item['status'];
                            $result[$wk]['sesi'][$i] = $item['jam_masuk'];

                            break;
                        } else {
                            $result[$wk]['tanggal'] = $wk;
                            $result[$wk]['nama'] = $history->nama;
                            $result[$wk]['nisn'] = $history->nisn;
                            $result[$wk]['sex'] = $history->sex;
                            //$result[$wk]['status'] = "";
                            $result[$wk]['sesi'][$i] = "";

                        }
                    } else {
                        $result[$wk]['tanggal'] = $wk;
                        $result[$wk]['nama'] = $history->nama;
                        $result[$wk]['nisn'] = $history->nisn;
                        $result[$wk]['sex'] = $history->sex;
                        $result[$wk]['sesi'][$i] = "";
                    }
                }
            }
        }
        return $result;
    }

}