<?php
/**
 * htdocs
 * RiwayatController.php
 * Author: DwiAgus
 * Email : dwiagus@uny.ac.id
 * Date  : 14/07/2020
 * Time  : 23:08
 */

namespace Modules\Presensi\Controllers;


use Modules\Frontend\Controllers\ControllerBase;
use Modules\History\Models\History;
use Modules\Presensi\Plugin\Helper;
use Modules\Webconfig\Models\Webconfig;
use Phalcon\Mvc\View;

class RiwayatController extends ControllerBase
{


    /**
     * @var mixed|void
     */
    private $terlambat;
    /**
     * @var mixed|void
     */
    private $pulangawal_jumat;
    /**
     * @var mixed|void
     */
    private $pulangawal_normal;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->assets
            ->collection('footer')
            ->setTargetPath("themes/admin/assets/js/combined-riwayat-presensi.js")
            ->setTargetUri("themes/admin/assets/js/combined-riwayat-presensi.js")
            ->join(true)
            ->addJs($this->config->application->addonsDir."presensi/views/js/riwayat.js")
            ->addFilter(new \Phalcon\Assets\Filters\Jsmin());

        foreach (Webconfig::find()->toArray() as $k => $v) {
            if($v['name'] == 'jam_terlambat'){
                $this->terlambat = $v['content'];
            }
            if($v['name'] == 'jam_pulang_awal_jumat'){
                $this->pulangawal_jumat = $v['content'];
            }
            if($v['name'] == 'jam_pulang_awal_normal'){
                $this->pulangawal_normal = $v['content'];
            }
        }
    }

    public function harianAction()
    {

    }

    public function bulananAction()
    {
        $this->view->pick("riwayat/index_bulanan");
    }

    public function search_bulananAction()
    {
        $mode   = $this->request->getPost('mode');
        $siswa  = $this->request->getPost('siswa_id');
        $bulan  = $this->request->getPost('bulan');
        $nisn   = $this->request->getPost('siswa_nisn');
        $arr = $this->personalBulanan($mode,$nisn,$bulan);

        $this->view->setRenderLevel(
            View::LEVEL_ACTION_VIEW
        );
        $this->view->setVar('work',Helper::workBulanan($bulan));
        $this->view->setVar('arr',$arr);
        if($mode == 0){
            $this->view->pick('riwayat/riwayat_normal_bulanan');
        }else{
            $this->view->pick('riwayat/riwayat_normal_bulanan');
        }

    }

    public function personalHarian($mode,$nisn,$tanggal)
    {
        if ($mode == 0) {
            $isMode = 'AND sesi=0';
        } else {
            $isMode = 'AND sesi <> 0';
        }
        $presensi = History::find([
            'conditions' => 'nisn= ?1',
            'bind' => [
                1 => $nisn,
            ]
        ]);
        $arr = array();
        foreach ($presensi as $siswa) {
            $arr[] = [
                'nisn' => $siswa->nisn,
                'nama' => $siswa->nama,
                'sex' => $siswa->sex,
                'presensi' => $siswa->getPresensi(
                    ['conditions' => "tanggal = '{$tanggal}' " . $isMode]),
            ];
        }
        return $arr;

    }

    public function personalBulanan($mode, $nisn, $bulan)
    {
        if ($mode == 0) {
            $isMode = 'AND sesi=0';
        } else {
            $isMode = 'AND sesi <> 0';
        }
        $history = History::findFirst([
            'conditions' => "nisn= ?1",
            'bind' => [
                1 => $nisn,
            ]
        ]);
        $arr = [
            'nisn' => $history->nisn,
            'nama' => $history->nama,
            'sex' => $history->sex,
            'presensi' => $history->getPresensi(
                ['conditions' => "DATE_FORMAT(tanggal,'%m-%Y') = '{$bulan}' " . $isMode]),
        ];

        return $arr;
    }
}